name: C/C++ CI

on:
  create:
     tag:
       - v*
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: fedora

    steps:
    - uses: actions/checkout@v3
    - name: git clone
      run: git clone git://github.com/cernekee/stoken
    - name: change directory cd stoken
      run: cd stoken
    - name: bash autogen.sh
      run: bash autogen.sh
    - name: mingw32-configure
      run: mingw32-configure
    - name: make winpkg
      run: make winpkg
